### ISSUE TITLE
Web-admin stuck on loading

### ISSUE THREAD

**Issue by sdekna** [ever-co/ever-demand#1508]
Hi all,

I have successfully built the apps and ran servers for core and web-admin... however when I log to localhost:4200, I get stuck indefinately in the loading screen.

![Screenshot_2022-07-31-22-12-31-242_com.android.chrome.jpg](https://user-images.githubusercontent.com/51303098/182043677-6e59e68c-4f34-473b-b5fa-037dbee3250c.jpg)

Am I doing something wrong?

**Comment by evereq** [comment]
@sdekna , please check the networking tab in Chrome dev tools to see requests to API. Most probably they did not succeed and it try to connect to localhost instead of your external IP etc. You need to configure the web frontend to connect to the correct API endpoint on your server and open firewalls on your server for such access. 

Afraid we can't add more about this issue here as it's very common to many different apps and not something specific to Gauzy platform.
