### ISSUE TITLE
Quick fire-up with docker 

### ISSUE THREAD

**Issue by sdekna** [ever-co/ever-demand#1511]
Hi all,

I spent days trying to work my way through dockerizing the project... and I'm thinking of making a separate docker-compose with enhanced dockerfiles to quickly build and deploy apps apps without the need to have deep technical background to navigate your way through it. Would this be something that you, as project maintainers, be interested in? If yes I can prepare it and send you a pull request.

Thanks.

**Comment by evereq** [comment]
@sdekna of course feel free to create PR for us to review, thank you!

**Comment by evereq** [comment]
Just make sure you saw https://github.com/ever-co/ever-demand/tree/develop/.deploy folder with many of existed Dockerfiles etc.

**Comment by sdekna** [comment]
Excellent!
Will get right through it.

**Comment by sdekna** [comment]
I am nearly done with api and admin, however, I am having trouble with passing environmental variables to angular apps through docker...

I tried with .env, however, the app seems to take all the environmental variables from "/packages/admin-web-angular/scripts/env.ts", and I am not sure how to pass environments variables to it.

Any help would be appreciated.

**Comment by evereq** [comment]
Sorry, it's hard for me to follow what exactly you are doing because think we have all that already in https://github.com/ever-co/ever-demand/blob/develop/.deploy/admin-web-angular/entrypoint.prod.sh#L6

Did you review how our Dockers are created / used before building your own? What would be the difference between our existed implementation and yours?
